SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population]
      ,[new_vaccinations]
      ,[RollingCount]
  FROM [Portfolio Project].[dbo].[PercentPopulationVaccinated]
